# The id of the video source that sends the intersection video
leeds:
  # The points define a polygon in the frame that delimits the intersection
  points:
    - [140, 465]
    - [250, 295]
    - [465, 190]
    - [840, 125]
    - [1565, 440]
    - [1295, 760]

  # Edges list contain the string tags for the polygon edges.
  # The 1st list element is the edge between the 1st and the 2nd points from the list above,
  # the 2nd is the edge between the 2nd and 3rd points and so on.
  # If the edge tag is null, then it is disabled:
  # the edge is not drawn on the frame and the crossings are not checked for it.
  # Do not use "->" or "+" in the edge tags
  # as these strings serve as separators for dynamically generated crossing direction names
  edges:
    - left
    - null
    - top
    - null
    - bottom
    - null

# for the performance module config
'0':
  points:
    - [140, 465]
    - [250, 295]
    - [465, 190]
    - [840, 125]
    - [1565, 440]
    - [1295, 760]

  edges:
    - left
    - null
    - top
    - null
    - bottom
    - null

'source-0':
  points:
    - [140, 465]
    - [250, 295]
    - [465, 190]
    - [840, 125]
    - [1565, 440]
    - [1295, 760]

  edges:
    - left
    - null
    - top
    - null
    - bottom
    - null

'source-1':
  points:
    - [140, 465]
    - [250, 295]
    - [465, 190]
    - [840, 125]
    - [1565, 440]
    - [1295, 760]

  edges:
    - left
    - null
    - top
    - null
    - bottom
    - null

'source-2':
  points:
    - [140, 465]
    - [250, 295]
    - [465, 190]
    - [840, 125]
    - [1565, 440]
    - [1295, 760]

  edges:
    - left
    - null
    - top
    - null
    - bottom
    - null

'source-3':
  points:
    - [140, 465]
    - [250, 295]
    - [465, 190]
    - [840, 125]
    - [1565, 440]
    - [1295, 760]

  edges:
    - left
    - null
    - top
    - null
    - bottom
    - null

'source-4':
  points:
    - [140, 465]
    - [250, 295]
    - [465, 190]
    - [840, 125]
    - [1565, 440]
    - [1295, 760]

  edges:
    - left
    - null
    - top
    - null
    - bottom
    - null

'source-5':
  points:
    - [140, 465]
    - [250, 295]
    - [465, 190]
    - [840, 125]
    - [1565, 440]
    - [1295, 760]

  edges:
    - left
    - null
    - top
    - null
    - bottom
    - null

'source-6':
  points:
    - [140, 465]
    - [250, 295]
    - [465, 190]
    - [840, 125]
    - [1565, 440]
    - [1295, 760]

  edges:
    - left
    - null
    - top
    - null
    - bottom
    - null

'source-7':
  points:
    - [140, 465]
    - [250, 295]
    - [465, 190]
    - [840, 125]
    - [1565, 440]
    - [1295, 760]

  edges:
    - left
    - null
    - top
    - null
    - bottom
    - null
