version: "3.3"
services:

  gige-camera-raw:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer:0.2.5
    restart: unless-stopped
    entrypoint: arv-fake-gv-camera-0.8
    command: [ "-i", "eth0", "-s", "Camera-Raw" ]

  gige-camera-encoded:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer:0.2.5
    restart: unless-stopped
    entrypoint: arv-fake-gv-camera-0.8
    command: [ "-i", "eth0", "-s", "Camera-Encoded" ]

  gige-source-raw:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer:0.2.5
    restart: unless-stopped
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
    environment:
      - CAMERA_NAME=Aravis-Fake-Camera-Raw
      - FRAMERATE=20/1
      - ENCODE=False
      - ZMQ_ENDPOINT=pub+connect:ipc:///tmp/zmq-sockets/video.ipc
      - SOURCE_ID=gige-raw
    entrypoint: /opt/savant/adapters/gst/sources/gige_cam.sh

  gige-source-encoded:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer:0.2.5
    restart: unless-stopped
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
    environment:
      - CAMERA_NAME=Aravis-Fake-Camera-Encoded
      - FRAMERATE=20/1
      - ENCODE=True
      - ZMQ_ENDPOINT=pub+connect:ipc:///tmp/zmq-sockets/video.ipc
      - SOURCE_ID=gige-encoded
    entrypoint: /opt/savant/adapters/gst/sources/gige_cam.sh

  always-on-sink:
    image: ghcr.io/insight-platform/savant-adapters-deepstream:0.2.5-6.3
    restart: unless-stopped
    ports:
      - "554:554"    # RTSP
      - "1935:1935"  # RTMP
      - "888:888"    # HLS
      - "8889:8889"  # WebRTC
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ../assets/stub_imgs:/stub_imgs
    environment:
      - ZMQ_ENDPOINT=sub+bind:ipc:///tmp/zmq-sockets/video.ipc
      - SOURCE_IDS=gige-raw,gige-encoded
      - FRAMERATE=20/1
      - STUB_FILE_LOCATION=/stub_imgs/smpte100_1280x720.jpeg
      - DEV_MODE=True
    command: python -m adapters.ds.sinks.always_on_rtsp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  zmq_sockets:
