version: "3.3"
services:

  source:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer:0.4.0
    entrypoint: /opt/savant/adapters/gst/sources/multi_stream.sh
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ../../data/:/data
    environment:
      - LOCATION=/data/${INPUT_FILENAME}
      - SHUTDOWN_AUTH=shutdown
      - ZMQ_ENDPOINT=dealer+connect:ipc:///tmp/zmq-sockets/input-video.ipc
      - SOURCE_ID_PATTERN=animegan_result_%d
      - NUMBER_OF_STREAMS=1
      - RECEIVE_TIMEOUT=50000
    depends_on:
      module:
        condition: service_healthy

  module:
    image: ghcr.io/insight-platform/savant-deepstream:0.4.0-6.4
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ../../cache:/cache
      - ..:/opt/savant/samples
    command: samples/animegan/module.yml
    environment:
      - MODEL_PATH=/cache/models/animegan
      - DOWNLOAD_PATH=/cache/downloads/animegan
      - ZMQ_SRC_ENDPOINT=router+bind:ipc:///tmp/zmq-sockets/input-video.ipc
      - ZMQ_SINK_ENDPOINT=pub+bind:ipc:///tmp/zmq-sockets/output-video.ipc
      - METRICS_FRAME_PERIOD=1000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  video-sink:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer:0.4.0
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ../../data/results:/data
    environment:
      - ZMQ_ENDPOINT=sub+connect:ipc:///tmp/zmq-sockets/output-video.ipc
      - DIR_LOCATION=/data
      - SKIP_FRAMES_WITHOUT_OBJECTS=False
    entrypoint: /opt/savant/adapters/gst/sinks/video_files.py

volumes:
  zmq_sockets:
