services:

  index-builder-client:
    build:
      context: .
      dockerfile: docker/Dockerfile.l4t
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ./assets/gallery:/gallery
      - ./src:/opt/savant/samples/face_reid
      - ./index_files:/index
    environment:
      - ZMQ_SRC_ENDPOINT=req+connect:ipc:///tmp/zmq-sockets/input-video.ipc
      - ZMQ_SINK_ENDPOINT=sub+connect:ipc:///tmp/zmq-sockets/output-video.ipc
    entrypoint: python
    command: samples/face_reid/index_builder_client.py
    profiles:
      - index
    depends_on:
      index-builder-pipeline:
        condition: service_healthy

  index-builder-pipeline:
    image: ghcr.io/insight-platform/savant-deepstream-l4t:0.4.4-6.4
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ../../cache:/cache
      - ./src:/opt/savant/samples/face_reid
    command: samples/face_reid/index_builder.yml
    environment:
      - MODEL_PATH=/cache/models/face_reid
      - DOWNLOAD_PATH=/cache/downloads/face_reid
      - ZMQ_SRC_ENDPOINT=rep+bind:ipc:///tmp/zmq-sockets/input-video.ipc
      - ZMQ_SINK_ENDPOINT=pub+bind:ipc:///tmp/zmq-sockets/output-video.ipc
    runtime: nvidia
    profiles:
      - index

  video-loop-source:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer-l4t:0.4.4
    restart: unless-stopped
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - /tmp/video-loop-source-downloads:/tmp/video-loop-source-downloads
    environment:
      - LOCATION=https://eu-central-1.linodeobjects.com/savant-data/demo/jumanji_cast.mp4
      - DOWNLOAD_PATH=/tmp/video-loop-source-downloads
      - ZMQ_ENDPOINT=pub+connect:ipc:///tmp/zmq-sockets/input-video.ipc
      - SOURCE_ID=video
      - SYNC_OUTPUT=True
    entrypoint: /opt/savant/adapters/gst/sources/video_loop.sh
    profiles:
      - demo
    depends_on:
      module:
        condition: service_healthy

  module:
    build:
      context: .
      dockerfile: docker/Dockerfile.l4t
    restart: unless-stopped
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ../../cache:/cache
      - ./src:/opt/savant/samples/face_reid
      - ./index_files:/index
    command: samples/face_reid/module.yml
    environment:
      - MODEL_PATH=/cache/models/face_reid
      - DOWNLOAD_PATH=/cache/downloads/face_reid
      - ZMQ_SRC_ENDPOINT=sub+bind:ipc:///tmp/zmq-sockets/input-video.ipc
      - ZMQ_SINK_ENDPOINT=pub+bind:ipc:///tmp/zmq-sockets/output-video.ipc
      - METRICS_FRAME_PERIOD=1000
      - CODEC=jpeg
    runtime: nvidia
    profiles:
      - demo

  always-on-sink:
    image: ghcr.io/insight-platform/savant-adapters-deepstream-l4t:0.4.4-6.4
    restart: unless-stopped
    ports:
      - "554:554"    # RTSP
      - "1935:1935"  # RTMP
      - "888:888"    # HLS
      - "8889:8889"  # WebRTC
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ../assets/stub_imgs:/stub_imgs
    environment:
      - ZMQ_ENDPOINT=sub+connect:ipc:///tmp/zmq-sockets/output-video.ipc
      - SOURCE_ID=video
      - FRAMERATE=25/1
      - STUB_FILE_LOCATION=/stub_imgs/smpte100_1576x720.jpeg
      - DEV_MODE=True
    command: python -m adapters.ds.sinks.always_on_rtsp
    profiles:
      - demo

volumes:
  zmq_sockets:
