services:

  video-loop-source:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer-l4t:0.4.5
    restart: unless-stopped
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - /tmp/video-loop-source-downloads:/tmp/video-loop-source-downloads
    environment:
      - LOCATION=https://eu-central-1.linodeobjects.com/savant-data/demo/shuffle_dance_360p.mp4
      - DOWNLOAD_PATH=/tmp/video-loop-source-downloads
      - ZMQ_ENDPOINT=pub+connect:ipc:///tmp/zmq-sockets/input-video.ipc
      - SOURCE_ID=video
      - SYNC_OUTPUT=True
    entrypoint: /opt/savant/adapters/gst/sources/video_loop.sh
    depends_on:
      module:
        condition: service_healthy

  module:
    image: ghcr.io/insight-platform/savant-deepstream-l4t:0.4.5-6.4
    restart: unless-stopped
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ../../cache:/cache
      - ..:/opt/savant/samples
      # uncomment the following line to use a local model
      #- ./identity.onnx:/cache/models/bypass_model/identity-local/identity.onnx
    command: samples/bypass_model/demo.yml
    environment:
      - MODEL_PATH=/cache/models/bypass_model
      - DOWNLOAD_PATH=/cache/downloads/bypass_model
      - ZMQ_SRC_ENDPOINT=sub+bind:ipc:///tmp/zmq-sockets/input-video.ipc
      - ZMQ_SINK_ENDPOINT=pub+bind:ipc:///tmp/zmq-sockets/output-video.ipc
      - METRICS_FRAME_PERIOD=1000
    runtime: nvidia

  always-on-sink:
    image: ghcr.io/insight-platform/savant-adapters-deepstream-l4t:0.4.5-6.4
    restart: unless-stopped
    ports:
      - "554:554"    # RTSP
      - "1935:1935"  # RTMP
      - "888:888"    # HLS
      - "8889:8889"  # WebRTC
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ../assets/stub_imgs:/stub_imgs
    environment:
      - ZMQ_ENDPOINT=sub+connect:ipc:///tmp/zmq-sockets/output-video.ipc
      - SOURCE_ID=video-with-preprocessed-frame
      - STUB_FILE_LOCATION=/stub_imgs/smpte100_2160x720.jpeg
      - DEV_MODE=True
    command: python -m adapters.ds.sinks.always_on_rtsp

volumes:
  zmq_sockets:
