version: "3.3"
services:

  rtsp-city-traffic:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer-l4t:0.2.5
    restart: unless-stopped
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
    environment:
      - RTSP_URI=rtsp://hello.savant.video:8554/city-traffic
      - ZMQ_ENDPOINT=pub+connect:ipc:///tmp/zmq-sockets/input-video.ipc
      - SOURCE_ID=city-traffic
    entrypoint: /opt/savant/adapters/gst/sources/rtsp.sh
    depends_on:
      module:
        condition: service_healthy

  rtsp-town-centre:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer-l4t:0.2.5
    restart: unless-stopped
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
    environment:
      - RTSP_URI=rtsp://hello.savant.video:8554/town-centre
      - ZMQ_ENDPOINT=pub+connect:ipc:///tmp/zmq-sockets/input-video.ipc
      - SOURCE_ID=town-centre
    entrypoint: /opt/savant/adapters/gst/sources/rtsp.sh
    depends_on:
      module:
        condition: service_healthy

  module:
    image: ghcr.io/insight-platform/savant-deepstream-l4t:0.2.5-6.3
    restart: unless-stopped
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ../../models/peoplenet_detector:/models
      - ../../downloads/peoplenet_detector:/downloads
      - ..:/opt/savant/samples
    command: samples/multiple_rtsp/demo.yml
    environment:
      - ZMQ_SRC_ENDPOINT=sub+bind:ipc:///tmp/zmq-sockets/input-video.ipc
      - ZMQ_SINK_ENDPOINT=pub+bind:ipc:///tmp/zmq-sockets/output-video.ipc
      - FPS_PERIOD=1000
    runtime: nvidia

  always-on-sink:
    image: ghcr.io/insight-platform/savant-adapters-deepstream-l4t:0.2.5-6.3
    restart: unless-stopped
    ports:
      - "554:554"    # RTSP
      - "1935:1935"  # RTMP
      - "888:888"    # HLS
      - "8889:8889"  # WebRTC
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ../assets/stub_imgs:/stub_imgs
    environment:
      - ZMQ_ENDPOINT=sub+connect:ipc:///tmp/zmq-sockets/output-video.ipc
      - SOURCE_IDS=city-traffic,town-centre
      - FRAMERATE=25/1
      - STUB_FILE_LOCATION=/stub_imgs/smpte100_1280x720.jpeg
      - DEV_MODE=True
    command: python -m adapters.ds.sinks.always_on_rtsp
    runtime: nvidia

volumes:
  zmq_sockets:
